### ISSUE TITLE
Make internet connectivity checker interval configurable

### ISSUE THREAD

**Issue by danielspofford** [nerves-networking/vintage_net#191]
**Context**:

Devices are on unreliable networks with extreme bandwidth constraints.

**Issue**:

Pinging `1.1.1.1` (or anything) every 30 seconds indefinitely is far too aggressive for our use case and produces an untenable amount of traffic.

**Desire**:

Allow the min and max intervals of the internet checker to be configured by consumers of this library.

**Options**:

- compiletime configurable
- runtime configurable
- both

**Ref**:

https://github.com/nerves-networking/vintage_net/blob/715e5548cf4e488c09c9115887b213a48eff7d76/lib/vintage_net/interface/internet_connectivity_checker.ex#L17

**Curious to hear thoughts on**:

- Accepting a change in this vein.
- Implementation opinions.
- Are there any concerns if someone configured these checks to be on the order of once a day. Is it even worth doing them at that point? Is it feasible to just let the use of the interface drive this status and just disable this extra ping?

**Comment by jjcarstens** [comment]
I'd be content with making configurable at compile and runtime.

I can also see a case where one might not want this check going automatically or otherwise want to manage the concept of "connected vs disconnected" within their own setup so I can also backup being able to disable this checker. However, if disabled, I think we'd need a new property that's written to signify connection check is unreliable:
```elixir
iex()> VintageNet.get(["interface", "wlan0", "connection"])
:unchecked
```
(or `:not_monitored`, or `:check_disabled`...)

**Comment by mobileoverlord** [comment]
It would be nice to see if we could connect to anything internally in erlang that would let us assert that the lan connection is active. I believe its also desirable to have a way to unify this check so that multiple dependencies are not trying to always make the same assertion.
