### ISSUE TITLE
WiFi Password don't Keep in Plain Text

### ISSUE THREAD

**Issue by mattludwigs** [nerves-networking/vintage_net#7]
Example
https://hexdocs.pm/pbcs/readme.html

see 802.11i specs for more details

**Comment by fhunleth** [comment]
Just to add more context, I think we want to always convert WiFi passwords to their PSK form and use that rather than keep the WiFi password around at all. That feels slightly less embarrassing than someone looking at a MicroSD card and finding the WiFi password outright. 802.11i H.4. has details on that computation and it has similarities to the `pbcs` library, but I doubt any reused code.

Even storing the PSK in the clear makes me uncomfortable. That makes it feel like `pbcs` might have a role in obfuscating it. Since the device doesn't have a human operator, the "password" passed to `pbcs` will necessarily have to be constructed out of things that a determined person could find on the device since Nerves libraries can't count on secure memory.

**Comment by fhunleth** [comment]
Internally, we've been throwing away the passphrase and passing around the PSK. PR #25 obfuscates the PSK when it's persisted and it provides hooks to let users uses secrets that aren't hardcoded into their firmware images.
